name: Continuous Integration
on:
 push:
  paths-ignore:
    - 'documentation/**'
    - 'README.md'
 pull_request:
  paths-ignore:
    - 'documentation/**'
    - 'README.md'
jobs:
 build:
  name: Build and test
  runs-on: ubuntu-latest
  steps:
  -
    name: Checkout 
    uses: actions/checkout@v2
  -
    name: Build test container
    run: docker build --target test --tag my-test-image .
  -
    name: Run unit/integration tests
    run: docker run --env-file .env.test my-test-image tests
  -
    name: Run e2e tests
    run: docker run -e MONGO_CONNECTION_STRING=${{ secrets.MONGO_CONNECTION_STRING }} -e SECRET_KEY=${{ secrets.SECRET_KEY }} -e OAUTH_CLIENT_ID=${{ secrets.OAUTH_CLIENT_ID }} -e OAUTH_CLIENT_SECRET=${{ secrets.OAUTH_CLIENT_SECRET }} my-test-image tests_e2e
 publish:
  name: Publish build artifacts and deploy
  runs-on: ubuntu-latest
  needs: build
  if: github.ref == 'refs/heads/exercise-11'
  steps:
  -
    name: Checkout 
    uses: actions/checkout@v2
  -
    name: Login to docker hub
    run: echo ${{ secrets.DOCKER_HUB_PASSWORD }} | docker login -u ${{ secrets.DOCKER_HUB_USER }} --password-stdin
  -
    name: Build image 
    run: docker build --target production --tag ${{secrets.DOCKER_HUB_USER}}/devops-todoapp:$GITHUB_SHA --tag ${{secrets.DOCKER_HUB_USER}}/devops-todoapp:latest .
  -
    name: Push image
    run: docker push ${{secrets.DOCKER_HUB_USER}}/devops-todoapp:$GITHUB_SHA
  -
    name: Push image as latest
    run: docker push ${{secrets.DOCKER_HUB_USER}}/devops-todoapp:latest
  -
    name: Deploy to azure
    run: curl -dH -X POST "https://\$todo-app-llyh:${{ secrets.AZURE_DEPLOYMENT_PASSWORD}}@todo-app-llyh.scm.azurewebsites.net/docker/hook"
