name: Continuous Integration
on:
 push:
  paths-ignore:
    - 'documentation/**'
    - 'README.md'
 pull_request:
  paths-ignore:
    - 'documentation/**'
    - 'README.md'
jobs:
 build:
  name: Build and test
  runs-on: ubuntu-latest
  steps:
  -
    name: Checkout 
    uses: actions/checkout@v2
  -
    name: Build test container
    run: docker build --target test --tag my-test-image .
  -
    name: Run unit/integration tests
    run: docker run --env-file .env.test my-test-image tests
  -
    name: Run e2e tests
    run: docker run -e TRELLO_API_KEY=${{ secrets.TRELLO_API_KEY }} -e TRELLO_API_TOKEN=${{ secrets.TRELLO_API_TOKEN }} -e SECRET_KEY=${{ secrets.SECRET_KEY }} my-test-image tests_e2e
 publish:
  name: Publish build artifacts
  runs-on: ubuntu-latest
  needs: build
  if: github.ref == 'refs/heads/main'
  steps:
  -
    name: Checkout 
    uses: actions/checkout@v2
  -
    name: Login to docker hub
    run: echo ${{ secrets.DOCKER_HUB_PASSWORD }} | docker login -u ${{ secrets.DOCKER_HUB_USER }} --password-stdin
  -
    name: Build image 
    run: docker build --target production --tag ${{secrets.DOCKER_HUB_USER}}/devops-todoapp:$GITHUB_SHA .
  -
    name: Push image
    run: docker push ${{secrets.DOCKER_HUB_USER}}/devops-todoapp:$GITHUB_SHA
     
